weights: ''
cfg: ./models/yolov4-csp.yaml
data: /home/user/Desktop/Liveness Detection/Passive/Object Detection/data.yaml
hyp: data/hyp.scratch.yaml
epochs: 200
batch_size: 64
img_size:
- 416
- 416
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: true
name: yolov4-csp-results
device: 0,1,2,3
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
logdir: runs/
total_batch_size: 64
world_size: 1
global_rank: -1
